/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.asksunny.rpc.gateway;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DataType implements org.apache.thrift.TEnum {
  STRING(0),
  INTEGER(1),
  LONG(2),
  DOUBLE(3),
  SHORT(4),
  STRING_ARRAY(20),
  INTEGER_ARRAY(21),
  LONG_ARRAY(22),
  DOUBLE_ARRAY(23),
  SHORT_ARRAY(24),
  JSON(41),
  XML(42),
  VOID(99);

  private final int value;

  private DataType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DataType findByValue(int value) { 
    switch (value) {
      case 0:
        return STRING;
      case 1:
        return INTEGER;
      case 2:
        return LONG;
      case 3:
        return DOUBLE;
      case 4:
        return SHORT;
      case 20:
        return STRING_ARRAY;
      case 21:
        return INTEGER_ARRAY;
      case 22:
        return LONG_ARRAY;
      case 23:
        return DOUBLE_ARRAY;
      case 24:
        return SHORT_ARRAY;
      case 41:
        return JSON;
      case 42:
        return XML;
      case 99:
        return VOID;
      default:
        return null;
    }
  }
}
